services:
  - type: web_service
    name: smart-grocery-backend
    env: node
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: ""
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: ""
